# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQgBnzJIHvA3nSNbbF83J2L6_nOq0wPD
"""

n = 10
a = 0
b = 1

for i in range(n):
    print(a, end=" ")
    next = a + b
    a = b
    b = next